# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.
# source: cache_env.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

try:
    from google.protobuf import runtime_version as _runtime_version
    # Suppress gencode version mismatch if present
except ImportError:
    pass

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0f\x63\x61\x63he_env.proto\x12\tcache_env\"9\n\x0cResetRequest\x12\x0c\n\x04seed\x18\x01 \x01(\x03\x12\x0e\n\x06lambda\x18\x02 \x01(\x01\x12\x0b\n\x03\x65ta\x18\x03 \x01(\x01\"v\n\rStateResponse\x12\x0b\n\x03mem\x18\x01 \x01(\x01\x12\t\n\x01\x64\x18\x02 \x03(\x01\x12\t\n\x01y\x18\x03 \x03(\x01\x12\t\n\x01z\x18\x04 \x03(\x01\x12\t\n\x01\x62\x18\x05 \x03(\x05\x12\x16\n\x0erequested_file\x18\x06 \x01(\x05\x12\x14\n\x0c\x63urrent_time\x18\x07 \x01(\x01\"\x1d\n\x0bStepRequest\x12\x0e\n\x06\x61\x63tion\x18\x01 \x01(\x05\"\x81\x01\n\x0cStepResponse\x12,\n\nnext_state\x18\x01 \x01(\x0b\x32\x18.cache_env.StateResponse\x12\x0e\n\x06reward\x18\x02 \x01(\x01\x12\x0b\n\x03tau\x18\x03 \x01(\x01\x12\x0e\n\x06is_hit\x18\x04 \x01(\x08\x12\x16\n\x0eutility_gained\x18\x05 \x01(\x01\"#\n\x10\x42\x61tchStepRequest\x12\x0f\n\x07\x61\x63tions\x18\x01 \x03(\x05\"D\n\x11\x42\x61tchStepResponse\x12/\n\x0estep_responses\x18\x01 \x03(\x0b\x32\x17.cache_env.StepResponse2\xce\x01\n\x0f\x43\x61\x63heEnvService\x12:\n\x05Reset\x12\x17.cache_env.ResetRequest\x1a\x18.cache_env.StateResponse\x12\x37\n\x04Step\x12\x16.cache_env.StepRequest\x1a\x17.cache_env.StepResponse\x12\x46\n\tBatchStep\x12\x1b.cache_env.BatchStepRequest\x1a\x1c.cache_env.BatchStepResponseB$Z\"smdp-edge-caching-framework/pkg/pbb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cache_env_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals['DESCRIPTOR']._loaded_options = None
    _globals['DESCRIPTOR']._serialized_options = b'Z\"smdp-edge-caching-framework/pkg/pb'
    _globals['_RESETREQUEST']._serialized_start = 30
    _globals['_RESETREQUEST']._serialized_end = 87
    _globals['_STATERESPONSE']._serialized_start = 89
    _globals['_STATERESPONSE']._serialized_end = 207
    _globals['_STEPREQUEST']._serialized_start = 209
    _globals['_STEPREQUEST']._serialized_end = 238
    _globals['_STEPRESPONSE']._serialized_start = 241
    _globals['_STEPRESPONSE']._serialized_end = 370
    _globals['_BATCHSTEPREQUEST']._serialized_start = 372
    _globals['_BATCHSTEPREQUEST']._serialized_end = 407
    _globals['_BATCHSTEPRESPONSE']._serialized_start = 409
    _globals['_BATCHSTEPRESPONSE']._serialized_end = 477
    _globals['_CACHEENVSERVICE']._serialized_start = 480
    _globals['_CACHEENVSERVICE']._serialized_end = 686
