// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.35.1
// source: cache_env.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CacheEnvService_Reset_FullMethodName     = "/cache_env.CacheEnvService/Reset"
	CacheEnvService_Step_FullMethodName      = "/cache_env.CacheEnvService/Step"
	CacheEnvService_BatchStep_FullMethodName = "/cache_env.CacheEnvService/BatchStep"
)

// CacheEnvServiceClient is the client API for CacheEnvService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CacheEnvServiceClient interface {
	Reset(ctx context.Context, in *ResetRequest, opts ...grpc.CallOption) (*StateResponse, error)
	Step(ctx context.Context, in *StepRequest, opts ...grpc.CallOption) (*StepResponse, error)
	BatchStep(ctx context.Context, in *BatchStepRequest, opts ...grpc.CallOption) (*BatchStepResponse, error)
}

type cacheEnvServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCacheEnvServiceClient(cc grpc.ClientConnInterface) CacheEnvServiceClient {
	return &cacheEnvServiceClient{cc}
}

func (c *cacheEnvServiceClient) Reset(ctx context.Context, in *ResetRequest, opts ...grpc.CallOption) (*StateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StateResponse)
	err := c.cc.Invoke(ctx, CacheEnvService_Reset_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cacheEnvServiceClient) Step(ctx context.Context, in *StepRequest, opts ...grpc.CallOption) (*StepResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StepResponse)
	err := c.cc.Invoke(ctx, CacheEnvService_Step_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cacheEnvServiceClient) BatchStep(ctx context.Context, in *BatchStepRequest, opts ...grpc.CallOption) (*BatchStepResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchStepResponse)
	err := c.cc.Invoke(ctx, CacheEnvService_BatchStep_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CacheEnvServiceServer is the server API for CacheEnvService service.
// All implementations must embed UnimplementedCacheEnvServiceServer
// for forward compatibility.
type CacheEnvServiceServer interface {
	Reset(context.Context, *ResetRequest) (*StateResponse, error)
	Step(context.Context, *StepRequest) (*StepResponse, error)
	BatchStep(context.Context, *BatchStepRequest) (*BatchStepResponse, error)
	mustEmbedUnimplementedCacheEnvServiceServer()
}

// UnimplementedCacheEnvServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCacheEnvServiceServer struct{}

func (UnimplementedCacheEnvServiceServer) Reset(context.Context, *ResetRequest) (*StateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Reset not implemented")
}
func (UnimplementedCacheEnvServiceServer) Step(context.Context, *StepRequest) (*StepResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Step not implemented")
}
func (UnimplementedCacheEnvServiceServer) BatchStep(context.Context, *BatchStepRequest) (*BatchStepResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchStep not implemented")
}
func (UnimplementedCacheEnvServiceServer) mustEmbedUnimplementedCacheEnvServiceServer() {}
func (UnimplementedCacheEnvServiceServer) testEmbeddedByValue()                         {}

// UnsafeCacheEnvServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CacheEnvServiceServer will
// result in compilation errors.
type UnsafeCacheEnvServiceServer interface {
	mustEmbedUnimplementedCacheEnvServiceServer()
}

func RegisterCacheEnvServiceServer(s grpc.ServiceRegistrar, srv CacheEnvServiceServer) {
	// If the following call pancis, it indicates UnimplementedCacheEnvServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CacheEnvService_ServiceDesc, srv)
}

func _CacheEnvService_Reset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheEnvServiceServer).Reset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CacheEnvService_Reset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CacheEnvServiceServer).Reset(ctx, req.(*ResetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CacheEnvService_Step_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StepRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheEnvServiceServer).Step(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CacheEnvService_Step_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CacheEnvServiceServer).Step(ctx, req.(*StepRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CacheEnvService_BatchStep_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchStepRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheEnvServiceServer).BatchStep(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CacheEnvService_BatchStep_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CacheEnvServiceServer).BatchStep(ctx, req.(*BatchStepRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CacheEnvService_ServiceDesc is the grpc.ServiceDesc for CacheEnvService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CacheEnvService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cache_env.CacheEnvService",
	HandlerType: (*CacheEnvServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Reset",
			Handler:    _CacheEnvService_Reset_Handler,
		},
		{
			MethodName: "Step",
			Handler:    _CacheEnvService_Step_Handler,
		},
		{
			MethodName: "BatchStep",
			Handler:    _CacheEnvService_BatchStep_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cache_env.proto",
}
