// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.35.1
// source: cache_env.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seed          int64                  `protobuf:"varint,1,opt,name=seed,proto3" json:"seed,omitempty"`
	Lambda        float64                `protobuf:"fixed64,2,opt,name=lambda,proto3" json:"lambda,omitempty"`
	Eta           float64                `protobuf:"fixed64,3,opt,name=eta,proto3" json:"eta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetRequest) Reset() {
	*x = ResetRequest{}
	mi := &file_cache_env_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetRequest) ProtoMessage() {}

func (x *ResetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cache_env_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetRequest.ProtoReflect.Descriptor instead.
func (*ResetRequest) Descriptor() ([]byte, []int) {
	return file_cache_env_proto_rawDescGZIP(), []int{0}
}

func (x *ResetRequest) GetSeed() int64 {
	if x != nil {
		return x.Seed
	}
	return 0
}

func (x *ResetRequest) GetLambda() float64 {
	if x != nil {
		return x.Lambda
	}
	return 0
}

func (x *ResetRequest) GetEta() float64 {
	if x != nil {
		return x.Eta
	}
	return 0
}

type StateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mem           float64                `protobuf:"fixed64,1,opt,name=mem,proto3" json:"mem,omitempty"`                                         // Unoccupied memory proportion Mem(t)
	D             []float64              `protobuf:"fixed64,2,rep,packed,name=d,proto3" json:"d,omitempty"`                                      // Popularity window vector d(t)
	Y             []float64              `protobuf:"fixed64,3,rep,packed,name=y,proto3" json:"y,omitempty"`                                      // File utility vector y(t)
	Z             []float64              `protobuf:"fixed64,4,rep,packed,name=z,proto3" json:"z,omitempty"`                                      // File size vector z(t)
	B             []int32                `protobuf:"varint,5,rep,packed,name=b,proto3" json:"b,omitempty"`                                       // Binary cached indicator b(t)
	RequestedFile int32                  `protobuf:"varint,6,opt,name=requested_file,json=requestedFile,proto3" json:"requested_file,omitempty"` // Requested file index f_r
	CurrentTime   float64                `protobuf:"fixed64,7,opt,name=current_time,json=currentTime,proto3" json:"current_time,omitempty"`      // Physical simulation time t
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateResponse) Reset() {
	*x = StateResponse{}
	mi := &file_cache_env_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateResponse) ProtoMessage() {}

func (x *StateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cache_env_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateResponse.ProtoReflect.Descriptor instead.
func (*StateResponse) Descriptor() ([]byte, []int) {
	return file_cache_env_proto_rawDescGZIP(), []int{1}
}

func (x *StateResponse) GetMem() float64 {
	if x != nil {
		return x.Mem
	}
	return 0
}

func (x *StateResponse) GetD() []float64 {
	if x != nil {
		return x.D
	}
	return nil
}

func (x *StateResponse) GetY() []float64 {
	if x != nil {
		return x.Y
	}
	return nil
}

func (x *StateResponse) GetZ() []float64 {
	if x != nil {
		return x.Z
	}
	return nil
}

func (x *StateResponse) GetB() []int32 {
	if x != nil {
		return x.B
	}
	return nil
}

func (x *StateResponse) GetRequestedFile() int32 {
	if x != nil {
		return x.RequestedFile
	}
	return 0
}

func (x *StateResponse) GetCurrentTime() float64 {
	if x != nil {
		return x.CurrentTime
	}
	return 0
}

type StepRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        int32                  `protobuf:"varint,1,opt,name=action,proto3" json:"action,omitempty"` // 0 = Do not cache, 1 = Cache
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StepRequest) Reset() {
	*x = StepRequest{}
	mi := &file_cache_env_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StepRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepRequest) ProtoMessage() {}

func (x *StepRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cache_env_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepRequest.ProtoReflect.Descriptor instead.
func (*StepRequest) Descriptor() ([]byte, []int) {
	return file_cache_env_proto_rawDescGZIP(), []int{2}
}

func (x *StepRequest) GetAction() int32 {
	if x != nil {
		return x.Action
	}
	return 0
}

type StepResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NextState     *StateResponse         `protobuf:"bytes,1,opt,name=next_state,json=nextState,proto3" json:"next_state,omitempty"`
	Reward        float64                `protobuf:"fixed64,2,opt,name=reward,proto3" json:"reward,omitempty"`                                    // Instant reward r(t)
	Tau           float64                `protobuf:"fixed64,3,opt,name=tau,proto3" json:"tau,omitempty"`                                          // Poisson inter-arrival delta tau
	IsHit         bool                   `protobuf:"varint,4,opt,name=is_hit,json=isHit,proto3" json:"is_hit,omitempty"`                          // Whether current request was a cache hit
	UtilityGained float64                `protobuf:"fixed64,5,opt,name=utility_gained,json=utilityGained,proto3" json:"utility_gained,omitempty"` // Utility gained if hit
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StepResponse) Reset() {
	*x = StepResponse{}
	mi := &file_cache_env_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StepResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepResponse) ProtoMessage() {}

func (x *StepResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cache_env_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepResponse.ProtoReflect.Descriptor instead.
func (*StepResponse) Descriptor() ([]byte, []int) {
	return file_cache_env_proto_rawDescGZIP(), []int{3}
}

func (x *StepResponse) GetNextState() *StateResponse {
	if x != nil {
		return x.NextState
	}
	return nil
}

func (x *StepResponse) GetReward() float64 {
	if x != nil {
		return x.Reward
	}
	return 0
}

func (x *StepResponse) GetTau() float64 {
	if x != nil {
		return x.Tau
	}
	return 0
}

func (x *StepResponse) GetIsHit() bool {
	if x != nil {
		return x.IsHit
	}
	return false
}

func (x *StepResponse) GetUtilityGained() float64 {
	if x != nil {
		return x.UtilityGained
	}
	return 0
}

type BatchStepRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Actions       []int32                `protobuf:"varint,1,rep,packed,name=actions,proto3" json:"actions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchStepRequest) Reset() {
	*x = BatchStepRequest{}
	mi := &file_cache_env_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchStepRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchStepRequest) ProtoMessage() {}

func (x *BatchStepRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cache_env_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchStepRequest.ProtoReflect.Descriptor instead.
func (*BatchStepRequest) Descriptor() ([]byte, []int) {
	return file_cache_env_proto_rawDescGZIP(), []int{4}
}

func (x *BatchStepRequest) GetActions() []int32 {
	if x != nil {
		return x.Actions
	}
	return nil
}

type BatchStepResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StepResponses []*StepResponse        `protobuf:"bytes,1,rep,name=step_responses,json=stepResponses,proto3" json:"step_responses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchStepResponse) Reset() {
	*x = BatchStepResponse{}
	mi := &file_cache_env_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchStepResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchStepResponse) ProtoMessage() {}

func (x *BatchStepResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cache_env_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchStepResponse.ProtoReflect.Descriptor instead.
func (*BatchStepResponse) Descriptor() ([]byte, []int) {
	return file_cache_env_proto_rawDescGZIP(), []int{5}
}

func (x *BatchStepResponse) GetStepResponses() []*StepResponse {
	if x != nil {
		return x.StepResponses
	}
	return nil
}

var File_cache_env_proto protoreflect.FileDescriptor

const file_cache_env_proto_rawDesc = "" +
	"\n" +
	"\x0fcache_env.proto\x12\tcache_env\"L\n" +
	"\fResetRequest\x12\x12\n" +
	"\x04seed\x18\x01 \x01(\x03R\x04seed\x12\x16\n" +
	"\x06lambda\x18\x02 \x01(\x01R\x06lambda\x12\x10\n" +
	"\x03eta\x18\x03 \x01(\x01R\x03eta\"\xa3\x01\n" +
	"\rStateResponse\x12\x10\n" +
	"\x03mem\x18\x01 \x01(\x01R\x03mem\x12\f\n" +
	"\x01d\x18\x02 \x03(\x01R\x01d\x12\f\n" +
	"\x01y\x18\x03 \x03(\x01R\x01y\x12\f\n" +
	"\x01z\x18\x04 \x03(\x01R\x01z\x12\f\n" +
	"\x01b\x18\x05 \x03(\x05R\x01b\x12%\n" +
	"\x0erequested_file\x18\x06 \x01(\x05R\rrequestedFile\x12!\n" +
	"\fcurrent_time\x18\a \x01(\x01R\vcurrentTime\"%\n" +
	"\vStepRequest\x12\x16\n" +
	"\x06action\x18\x01 \x01(\x05R\x06action\"\xaf\x01\n" +
	"\fStepResponse\x127\n" +
	"\n" +
	"next_state\x18\x01 \x01(\v2\x18.cache_env.StateResponseR\tnextState\x12\x16\n" +
	"\x06reward\x18\x02 \x01(\x01R\x06reward\x12\x10\n" +
	"\x03tau\x18\x03 \x01(\x01R\x03tau\x12\x15\n" +
	"\x06is_hit\x18\x04 \x01(\bR\x05isHit\x12%\n" +
	"\x0eutility_gained\x18\x05 \x01(\x01R\rutilityGained\",\n" +
	"\x10BatchStepRequest\x12\x18\n" +
	"\aactions\x18\x01 \x03(\x05R\aactions\"S\n" +
	"\x11BatchStepResponse\x12>\n" +
	"\x0estep_responses\x18\x01 \x03(\v2\x17.cache_env.StepResponseR\rstepResponses2\xce\x01\n" +
	"\x0fCacheEnvService\x12:\n" +
	"\x05Reset\x12\x17.cache_env.ResetRequest\x1a\x18.cache_env.StateResponse\x127\n" +
	"\x04Step\x12\x16.cache_env.StepRequest\x1a\x17.cache_env.StepResponse\x12F\n" +
	"\tBatchStep\x12\x1b.cache_env.BatchStepRequest\x1a\x1c.cache_env.BatchStepResponseB$Z\"smdp-edge-caching-framework/pkg/pbb\x06proto3"

var (
	file_cache_env_proto_rawDescOnce sync.Once
	file_cache_env_proto_rawDescData []byte
)

func file_cache_env_proto_rawDescGZIP() []byte {
	file_cache_env_proto_rawDescOnce.Do(func() {
		file_cache_env_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cache_env_proto_rawDesc), len(file_cache_env_proto_rawDesc)))
	})
	return file_cache_env_proto_rawDescData
}

var file_cache_env_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_cache_env_proto_goTypes = []any{
	(*ResetRequest)(nil),      // 0: cache_env.ResetRequest
	(*StateResponse)(nil),     // 1: cache_env.StateResponse
	(*StepRequest)(nil),       // 2: cache_env.StepRequest
	(*StepResponse)(nil),      // 3: cache_env.StepResponse
	(*BatchStepRequest)(nil),  // 4: cache_env.BatchStepRequest
	(*BatchStepResponse)(nil), // 5: cache_env.BatchStepResponse
}
var file_cache_env_proto_depIdxs = []int32{
	1, // 0: cache_env.StepResponse.next_state:type_name -> cache_env.StateResponse
	3, // 1: cache_env.BatchStepResponse.step_responses:type_name -> cache_env.StepResponse
	0, // 2: cache_env.CacheEnvService.Reset:input_type -> cache_env.ResetRequest
	2, // 3: cache_env.CacheEnvService.Step:input_type -> cache_env.StepRequest
	4, // 4: cache_env.CacheEnvService.BatchStep:input_type -> cache_env.BatchStepRequest
	1, // 5: cache_env.CacheEnvService.Reset:output_type -> cache_env.StateResponse
	3, // 6: cache_env.CacheEnvService.Step:output_type -> cache_env.StepResponse
	5, // 7: cache_env.CacheEnvService.BatchStep:output_type -> cache_env.BatchStepResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_cache_env_proto_init() }
func file_cache_env_proto_init() {
	if File_cache_env_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cache_env_proto_rawDesc), len(file_cache_env_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cache_env_proto_goTypes,
		DependencyIndexes: file_cache_env_proto_depIdxs,
		MessageInfos:      file_cache_env_proto_msgTypes,
	}.Build()
	File_cache_env_proto = out.File
	file_cache_env_proto_goTypes = nil
	file_cache_env_proto_depIdxs = nil
}
